import { mkdirSync, writeFileSync } from 'node:fs';
import { home } from './home.mjs';
import { diagnosis, strategy } from './services.mjs';
import { legalPages } from './legal.mjs';

const origin = (process.env.SITE_URL || 'https://art-of-asking-questions.fit-eagle-4287.chatgpt.site').replace(/\/$/, '');
if (!/^https:\/\/[^/]+$/.test(origin)) throw new Error('SITE_URL must be an HTTPS origin without a path');
const isLive = process.env.SITE_LIVE === '1';
const brand = 'ART OF ASKING QUESTIONS';
const logo = `<img src="/assets/images/logo.png" width="1150" height="230" alt="${brand}" class="brand-logo">`;
const arrow = '<span class="arrow" aria-hidden="true">↗</span>';
const nav = `<a href="/#approach">Подход</a><a href="/diagnostika/">V+ Диагностика</a><a href="/strategiya/">V+2 Стратегия</a>`;
const header = `<a class="skip-link" href="#main">Перейти к содержанию</a>
<header class="site-header"><div class="header-inner"><a class="brand" href="/" aria-label="${brand} — главная">${logo}</a><nav class="desktop-nav" aria-label="Основная навигация">${nav}</nav><a class="button header-cta" href="#contact" data-contact>Обсудить задачу</a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="mobile-menu" aria-label="Открыть меню"><span></span><span></span></button></div></header>
<dialog class="mobile-menu" id="mobile-menu" aria-labelledby="menu-title"><div class="menu-top"><span class="eyebrow" id="menu-title">ART OF ASKING QUESTIONS</span><button type="button" class="close-button" data-close aria-label="Закрыть меню">×</button></div><nav aria-label="Мобильная навигация"><a href="/">Главная</a>${nav}<a href="#contact" data-contact>Обсудить задачу ${arrow}</a></nav><p class="menu-bottom">Точные вопросы.<br>Взвешенные решения.</p></dialog>`;
const cta = `<section class="closing-cta" id="contact" aria-labelledby="contact-heading"><h2 id="contact-heading">Начнём с правильных<br>вопросов.</h2><div><a class="button button-light" href="#contact" data-contact>Обсудить задачу ${arrow}</a><p>Обсудим ситуацию в компании<br>и определим первый шаг.</p><noscript><p>Обращения через сайт пока не принимаются. Контактные данные будут добавлены перед запуском.</p></noscript></div></section>`;
const footer = `<footer class="site-footer"><div class="footer-main"><a class="brand" href="/" aria-label="${brand} — главная">${logo}</a><nav aria-label="Навигация в подвале"><a href="/#approach">Подход</a><a href="/diagnostika/">V+</a><a href="/strategiya/">V+2</a><a href="#contact" data-contact>Контакты</a></nav><small>© ${brand}</small></div><div class="footer-legal"><a href="/privacy/">Конфиденциальность</a><a href="/consent/">Обработка данных</a><a href="/terms/">Условия использования</a><a href="/cookies/">Cookie</a><button type="button" data-cookie-settings>Настройки cookie</button></div></footer>`;
const dialogs = `<dialog class="contact-dialog" id="contact-dialog" aria-labelledby="contact-title"><div class="dialog-heading"><p class="eyebrow">Начало разговора</p><button class="close-button" type="button" data-close aria-label="Закрыть форму">×</button></div><h2 id="contact-title">Расскажите<br>о вашей задаче.</h2><p class="dialog-intro">Какой вопрос о бизнесе сейчас важнее всего?</p><form id="contact-form"><label>Ваше имя<input name="name" autocomplete="name" required maxlength="80" placeholder="Как к вам обращаться"></label><label>Электронная почта<input type="email" name="email" autocomplete="email" required maxlength="160" placeholder="name@company.ru"></label><label>Компания <span class="optional">необязательно</span><input name="company" autocomplete="organization" maxlength="160" placeholder="Название компании"></label><label>Задача<textarea name="message" rows="3" required minlength="10" maxlength="2000" placeholder="Что происходит и что хотите изменить"></textarea></label><p class="form-note">Сейчас можно подготовить текст обращения и скопировать его. Отправка через сайт ещё не подключена. Введённые данные не сохраняются сайтом и не передаются нам.</p><button class="button" type="submit">Скопировать обращение <span aria-hidden="true">↗</span></button><p id="form-status" role="status" aria-live="polite"></p><p class="form-legal"><a href="/privacy/">Политика конфиденциальности</a> · <a href="/consent/">Обработка персональных данных</a></p></form></dialog>
<aside class="cookie-banner" aria-label="Cookie и конфиденциальность" hidden><div><strong>Немного о конфиденциальности</strong><p>Мы сохраняем только ваш выбор настроек в браузере. Аналитика и рекламные cookie не используются. <a href="/cookies/">Подробнее</a></p></div><div class="cookie-actions"><button class="button button-small" type="button" data-cookie-save>Только необходимые</button><button class="text-button" type="button" data-cookie-settings>Настроить</button></div></aside>
<dialog class="cookie-dialog" id="cookie-dialog" aria-labelledby="cookie-title"><div class="dialog-heading"><p class="eyebrow">Ваш выбор</p><button type="button" class="close-button" data-close aria-label="Закрыть настройки cookie">×</button></div><h2 id="cookie-title">Настройки cookie</h2><p>На сайте нет аналитических и рекламных счётчиков. Шрифты и изображения загружаются с самого сайта.</p><div class="cookie-category"><div><strong>Необходимое хранение</strong><p>Ваш выбор на этом устройстве. Срок хранения — 180 дней.</p></div><span class="tag">Всегда включено</span></div><div class="cookie-category"><div><strong>Аналитика и реклама</strong><p>Данные о просмотрах не отправляются в системы аналитики.</p></div><span class="tag">Не используются</span></div><button class="button" type="button" data-cookie-save>Сохранить настройки</button><button class="text-button clear-cookie" type="button" data-cookie-clear>Удалить сохранённый выбор</button><p class="storage-status" role="status"></p><a class="fine-link" href="/cookies/">Как работает хранение данных</a></dialog>`;

const pages = [
  { path:'/', title:'Диагностика бизнеса и стратегический консалтинг для CEO', description:'ART OF ASKING QUESTIONS: независимая диагностика бизнеса V+ за 10 рабочих дней. Стратегия, системы и команда первых лиц в пакете V+2. От ясности к действию.', content:home, label:'Главная' },
  { path:'/diagnostika/', title:'V+ — диагностика бизнеса Owner-CEO X-Ray', description:'Независимая диагностика стратегии, команды, структуры и систем компании. 10 рабочих дней, 3 senior-эксперта, закрытая карта решений для собственника и CEO.', content:diagnosis, label:'V+ Диагностика', service:'Независимая диагностика бизнеса V+ Owner-CEO X-Ray' },
  { path:'/strategiya/', title:'V+2 — стратегия и команда для развития бизнеса', description:'Owner-CEO Strategic Pack: стратегический контур, структуры, системы, корпоративная культура и команда первых лиц. 25 рабочих дней. Гонорар после финансового результата.', content:strategy, label:'V+2 Стратегия', service:'Стратегический консалтинг V+2 Owner-CEO Strategic Pack' },
  ...legalPages
];
for (const page of pages) {
  const url = origin + page.path;
  const crumbs = page.path === '/' ? '' : `<nav class="breadcrumbs" aria-label="Хлебные крошки"><a href="/">Главная</a><span aria-hidden="true">/</span><span aria-current="page">${page.label}</span></nav>`;
  const graph = [{ '@type':'Organization','@id':origin+'/#organization',name:brand,url:origin,logo:origin+'/assets/images/logo.png' },{ '@type':'WebSite','@id':origin+'/#website',name:brand,url:origin,inLanguage:'ru' },{ '@type':'WebPage','@id':url+'#webpage',url,name:page.title,description:page.description,inLanguage:'ru',isPartOf:{'@id':origin+'/#website'} }];
  if(page.service) graph.push({'@type':'Service',name:page.service,provider:{'@id':origin+'/#organization'},url});
  if(page.path!=='/') graph.push({'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Главная',item:origin+'/'},{'@type':'ListItem',position:2,name:page.label,item:url}]});
  const html = `<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light"><meta name="theme-color" content="#123f36"><title>${page.title} | ${brand}</title><meta name="description" content="${page.description}"><meta name="robots" content="${isLive&&!page.draft?'index, follow':'noindex, nofollow'}"><link rel="canonical" href="${url}"><meta property="og:type" content="website"><meta property="og:locale" content="ru_RU"><meta property="og:site_name" content="${brand}"><meta property="og:title" content="${page.title}"><meta property="og:description" content="${page.description}"><meta property="og:url" content="${url}"><meta property="og:image" content="${origin}/assets/images/hero-1600.webp"><meta property="og:image:alt" content="Светлая архитектурная лестница среди зелени"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/assets/images/favicon.png" type="image/png"><link rel="preload" href="/assets/fonts/manrope-regular.ttf" as="font" type="font/ttf" crossorigin><link rel="stylesheet" href="/assets/styles.css">${page.path==='/'?'<link rel="preload" as="image" href="/assets/images/hero-1600.webp" imagesrcset="/assets/images/hero-800.webp 800w, /assets/images/hero-1600.webp 1448w" imagesizes="(max-width: 700px) 100vw, 55vw">':''}<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@graph':graph})}</script><script type="module" src="/assets/app.js"></script></head><body>${header}<main id="main" tabindex="-1" class="page-container ${page.draft?'legal-page':''}">${crumbs}${page.content}${cta}</main>${footer}${dialogs}</body></html>`;
  const dir = `dist${page.path}`;
  mkdirSync(dir,{recursive:true}); writeFileSync(dir+'index.html',html.replaceAll('<br>', '<br> '));
}
const indexed = pages.filter(p=>!p.draft);
writeFileSync('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${indexed.map(p=>`<url><loc>${origin+p.path}</loc></url>`).join('')}</urlset>`);
writeFileSync('dist/robots.txt',isLive?`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`:'User-agent: *\nDisallow: /\n');
writeFileSync('dist/_headers',`/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n  X-Frame-Options: SAMEORIGIN\n/assets/*\n  Cache-Control: public, max-age=86400\n`);
writeFileSync('dist/404.html',`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>Страница не найдена | ${brand}</title><link rel="stylesheet" href="/assets/styles.css"></head><body><main class="not-found"><p class="eyebrow">404</p><h1>Кажется, здесь<br>другой вопрос.</h1><p>Этой страницы нет. Начните с главной.</p><a class="button" href="/">На главную ${arrow}</a></main></body></html>`);
console.log(`Generated ${pages.length} pages. ${isLive?'Indexing enabled for approved routes':'Preview: noindex'}.`);
